### ISSUE TITLE
Future request!

### ISSUE THREAD

**Issue by emrekocyatagi** [rototor/jeuclid#11]
Hey Dear Emmeran Seehuber,
Do you have any plan to add jeuclid-cli version in master or the latest version.

**Comment by rototor** [comment]
At the moment I have no plans at all to do anything here. I only use this library very sparse myself. If you provide a pull requests I'm willing to review and integrate them. And create a new release.

But I won't do any new development here.

**Comment by emrekocyatagi** [comment]
Okay, Thanks anyway.
