### ISSUE TITLE
Converting to MathML

### ISSUE THREAD

**Issue by AntonAMorozov** [rototor/jeuclid#17]
Hello!
Can this library simply convert Latex string to MathML String?
I didn't find how to do this

**Comment by rototor** [comment]
You can look here: https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-latex-support/src/main/java/com/openhtmltopdf/latexsupport/DOMConverter.java

In the end it boils down to this two statements:

```
...
session.parseInput(input);
...
session.buildDOMSubtree(latexElement, options);
...
```

**Comment by AntonAMorozov** [comment]
Unfortunately, this lib uses snuggletex library, which is very old and don't supports some kind of latex formulas( I need something like MarhJax, but for Java

**Comment by rototor** [comment]
Did you consider running MathJax inside RhinoJS? No idea, if to much DOM would be missing.

**Comment by AntonAMorozov** [comment]
No, just like this.
Input: \frac{\sum (r_{i-5})}{N}
Output: `<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mfrac>
    <mrow>
      <mo data-mjx-texclass="OP">&#x2211;</mo>
      <mo stretchy="false">(</mo>
      <msub>
        <mi>r</mi>
        <mrow data-mjx-texclass="ORD">
          <mi>i</mi>
          <mo>&#x2212;</mo>
          <mn>5</mn>
        </mrow>
      </msub>
      <mo stretchy="false">)</mo>
    </mrow>
    <mi>N</mi>
  </mfrac>
</math>`
It is all that I need) could jeuclid do this?

**Comment by rototor** [comment]
To be honest, no idea. I've took this old and unmaintained code and made it work with JDK9+. Thats more or less all I did. So I really don't have any idea about the internal details. 

And nowadays I even don't have a need for this library - beside having no time to work on it anyway... 

Sorry, but I cant help you here.
