### ISSUE TITLE
update xmlgraphics-commons to v2.2

### ISSUE THREAD

**Issue by markushenninger** [rototor/jeuclid#4]
`batik:1.9` has a dependency on `xmlgraphics-commons:2.2`. I made a pull request to update that.

Trying to build the project with `mvn clean verify` I got the error:

```
[ERROR] Unresolveable build extension: Plugin de.rototor.jeuclid:build-tools:1.0.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for de.rototor.jeuclid:build-tools:jar:1.0.5 @ 
```

Could you publish this class so that we can build JEuclid, please.

**Comment by rototor** [comment]
Well, building this project is tricky... You first must do a ```mvn install```
in the support directory. Otherwise you can't build it... As my primary target was to get this project running on JDK9+ I did not try to change / fix this.
